import '../models/animal.dart';
import 'package:uuid/uuid.dart';

final Uuid uuid = Uuid();

List<Animal> animalList = [
  Animal(
    ownerId: 'A2f0BNbeIrRXlqEDoM6uvp15kXv2',
    id: uuid.v4(),
    imageUrl: 'assets/images/dog-1.jpg',
    name: 'Max',
    gender: 'Male',
    type: 'Dog',
    size: 'Medium',
    age: 3,
    description: 'Max is a friendly and energetic dog who loves to play fetch and go on long walks. He is very loyal to his owners and gets along well with other pets. Max is always ready for an adventure and loves to meet new people.',
    personality: ['Playful'],
    isAdopted: false,
  ),
  Animal(
    ownerId: 'A2f0BNbeIrRXlqEDoM6uvp15kXv2',
    id: uuid.v4(),
    imageUrl: 'assets/images/cat-1.jpg',
    name: 'Bella',
    gender: 'Female',
    type: 'Cat',
    size: 'Small',
    age: 2,
    description: 'Bella is a curious and independent cat who enjoys exploring her surroundings. She is quite the observer and loves to perch herself in high places to watch over everything. Bella is also very affectionate and enjoys quiet moments with her human friends.',
    personality: ['Curious', 'Independent', 'Quiet'],
    isAdopted: false,
  ),
  Animal(
    ownerId: 'A2f0BNbeIrRXlqEDoM6uvp15kXv2',
    id: uuid.v4(),
    imageUrl: 'assets/images/rabbit-1.jpg',
    name: 'Charlie',
    gender: 'Male',
    type: 'Rabbit',
    size: 'Small',
    age: 1,
    description: 'Charlie is a gentle and cuddly rabbit who loves to be held and petted. He enjoys munching on fresh vegetables and hopping around the garden. Charlie is very calm and quiet, making him a perfect companion for a peaceful home.',
    personality: ['Gentle', 'Cuddly', 'Quiet'],
    isAdopted: false,
  ),
  Animal(
    ownerId: 'A2f0BNbeIrRXlqEDoM6uvp15kXv2',
    id: uuid.v4(),
    imageUrl: 'assets/images/bird-1.jpg',
    name: 'Lucy',
    gender: 'Female',
    type: 'Bird',
    size: 'Small',
    age: 4,
    description: 'Lucy is a vibrant and talkative parrot who loves to interact with people. She enjoys mimicking sounds and having conversations. Lucy is very intelligent and can learn new tricks quickly. She brings a lot of joy and color to her surroundings.',
    personality: ['Talkative', 'Vibrant', 'Intelligent'],
    isAdopted: false,
  ),
  Animal(
    ownerId: 'A2f0BNbeIrRXlqEDoM6uvp15kXv2',
    id: uuid.v4(),
    imageUrl: 'assets/images/dog-2.jpg',
    name: 'Max',
    gender: 'Male',
    type: 'Dog',
    size: 'Medium',
    age: 3,
    description: 'Max is a friendly and energetic dog who loves to play fetch and go on long walks. He is very loyal to his owners and gets along well with other pets. Max is always ready for an adventure and loves to meet new people.',
    personality: ['Playful', 'Loyal', 'Friendly'],
    isAdopted: false,
  ),
  Animal(
    ownerId: 'A2f0BNbeIrRXlqEDoM6uvp15kXv2',
    id: uuid.v4(),
    imageUrl: 'assets/images/cat-2.jpg',
    name: 'Bella',
    gender: 'Female',
    type: 'Cat',
    size: 'Small',
    age: 2,
    description: 'Bella is a curious and independent cat who enjoys exploring her surroundings. She is quite the observer and loves to perch herself in high places to watch over everything. Bella is also very affectionate and enjoys quiet moments with her human friends.',
    personality: ['Curious', 'Independent', 'Quiet'],
    isAdopted: false,
  ),
  Animal(
    ownerId: 'A2f0BNbeIrRXlqEDoM6uvp15kXv2',
    id: uuid.v4(),
    imageUrl: 'assets/images/dog-3.jpg',
    name: 'Max',
    gender: 'Male',
    type: 'Dog',
    size: 'Medium',
    age: 3,
    description: 'Max is a friendly and energetic dog who loves to play fetch and go on long walks. He is very loyal to his owners and gets along well with other pets. Max is always ready for an adventure and loves to meet new people.',
    personality: ['Playful', 'Loyal', 'Friendly'],
    isAdopted: false,
  ),
  Animal(
    ownerId: 'qR9a2OnCXoWCiOqHB67uDrZ2byB3',
    id: uuid.v4(),
    imageUrl: 'assets/images/cat-3.jpg',
    name: 'Bella',
    gender: 'Female',
    type: 'Cat',
    size: 'Small',
    age: 2,
    description: 'Bella is a curious and independent cat who enjoys exploring her surroundings. She is quite the observer and loves to perch herself in high places to watch over everything. Bella is also very affectionate and enjoys quiet moments with her human friends.',
    personality: ['Curious', 'Independent', 'Quiet', 'Lovely', 'Cute'],
    isAdopted: false,
  ),
];

Animal? getAnimalById(String id) {
  return animalList.firstWhere((animal) => animal.id == id);
  // Return null if no animal with the given id is found with ? operator
}