import '../models/animal.dart';
import 'package:uuid/uuid.dart';

final Uuid uuid = Uuid();

List<Animal> animalList = [
  Animal(
    id: uuid.v4(),
    name: 'Max',
    gender: 'Male',
    type: 'Dog',
    size: 'Medium',
    age: 3,
    description: 'A friendly and energetic dog.',
    personality: ['Playful', 'Loyal', 'Friendly'],
  ),
  Animal(
    id: uuid.v4(),
    name: 'Bella',
    gender: 'Female',
    type: 'Cat',
    size: 'Small',
    age: 2,
    description: 'A curious and independent cat.',
    personality: ['Curious', 'Independent', 'Quiet'],
  ),
  Animal(
    id: uuid.v4(),
    name: 'Charlie',
    gender: 'Male',
    type: 'Rabbit',
    size: 'Small',
    age: 1,
    description: 'A gentle and cuddly rabbit.',
    personality: ['Gentle', 'Cuddly', 'Quiet'],
  ),
  Animal(
    id: uuid.v4(),
    name: 'Lucy',
    gender: 'Female',
    type: 'Bird',
    size: 'Small',
    age: 4,
    description: 'A vibrant and talkative parrot.',
    personality: ['Talkative', 'Vibrant', 'Intelligent'],
  ),
  Animal(
    id: uuid.v4(),
    name: 'Max',
    gender: 'Male',
    type: 'Dog',
    size: 'Medium',
    age: 3,
    description: 'A friendly and energetic dog.',
    personality: ['Playful', 'Loyal', 'Friendly'],
  ),
  Animal(
    id: uuid.v4(),
    name: 'Bella',
    gender: 'Female',
    type: 'Cat',
    size: 'Small',
    age: 2,
    description: 'A curious and independent cat.',
    personality: ['Curious', 'Independent', 'Quiet'],
  ),
  Animal(
    id: uuid.v4(),
    name: 'Max',
    gender: 'Male',
    type: 'Dog',
    size: 'Medium',
    age: 3,
    description: 'A friendly and energetic dog.',
    personality: ['Playful', 'Loyal', 'Friendly'],
  ),
  Animal(
    id: uuid.v4(),
    name: 'Bella',
    gender: 'Female',
    type: 'Cat',
    size: 'Small',
    age: 2,
    description: 'A curious and independent cat.',
    personality: ['Curious', 'Independent', 'Quiet'],
  ),
];
